/*******************************************************************************
* This file is automatically generated by PSoC Creator
* and should not be edited by hand.
*
* This file is necessary for your project to build.
* Please do not delete it.
********************************************************************************
* Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/
#ifndef DEVICE_H
#define DEVICE_H

#include <project.h>

#include "main.h"
#include "i2c_comm.h"
#include "init.h"
#include "measure.h"
#include "rtd.h"
#include "uart_command.h"
#include "state_machine.h"
#include "timing.h"
#include "pwm_pi.h"
#include "display.h"
#include "lowpower.h"
#include "selftest.h"
#include "ftoa_itoa.h"


#endif
/* [] END OF FILE */
